name: Tests

on: [push, workflow_dispatch]

jobs:
  Test:
    strategy:
      matrix:
        python-verion: ["3.5.4", "3.7", "3.8", "3.9", "3.10"]

    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install test dependencies
        run: python -m pip install --quiet wheel setuptools coverage

      - name: Build wheel
        run: python setup.py bdist_wheel

      - name: run tests and generate coverage report
        run: |
          coverage run -m unittest discover --verbose -s tests
          coverage xml

      - name: Upload coverage
        uses: codecov/codecov-action@v2

  Typecheck:
    runs-on: "ubuntu-latest"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Python setup
        uses: actions/setup-python@v2
        with:
          python-verion: "3.10"

      - name: install typechecking dependencies
        run: python -m pip install --quiet mypy

      - name: run MyPy
        run: python -m mypy --config-file setup.cfg -p ascii_progress